version: '3'

services:
  frontend:
    image: task-management-frontend
    ports:
      - "3000:3000"
  backend:
    image: task-management-backend
    ports:
      - "3001:3001"
    environment:
      - AWS_ACCESS_KEY_ID=${aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}

